jwt:
  secret: jwtsecretkey
spring:
  datasource:
    password: Fibonacci12358
    platform: mysql
    url: jdbc:mysql://localhost:3306/security_study?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update